services:
  drupal:
    image: drupal:11.1.3-php8.4 # Official Drupal Docker image (version 9)
    container_name: drupal
    ports:
      - "8080:80" # Maps the container's port 80 to localhost's port 8080
    volumes:
      - drupal:/var/www/html
    depends_on:
      - db
    networks:
      - drupal-network
  db:
    image: mariadb:11.7.2-ubi9
    container_name: drupal-db
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql-root-password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: /run/secrets/mysql-password
    volumes:
      - db-data:/var/lib/mysql # Persistent storage for the database
    networks:
      - drupal-network
  phpmyadmin:
    image: phpmyadmin:5-apache # phpMyAdmin for easy database management
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - drupal-network
networks:
  drupal-network:
    driver: bridgegit
volumes:
  db-data:
  drupal:
secrets:
  mysql-root-password:
    environment: MYSQL_ROOT_PASSWORD
  mysql-password:
    environment: MYSQL_PASSWORD
